const positions=['Intern','Associate','Supervisor','Manager','Director','VP','CEO'];
const bosses=[{name:'HR Gatekeeper',icon:'👩‍💼',hp:10,attack:1,line:'DID YOU FILL OUT YOUR SELF-REVIEW?'},{name:'CFO of Doom',icon:'🧛‍♂️',hp:14,attack:2,line:'YOUR JOY IS NOT IN THE BUDGET.'},{name:'CEO Final Form',icon:'👑',hp:18,attack:3,line:'WE ARE A FAMILY. OBEY.'}];
const personas=[
{name:'Intern Prodigy',icon:'🧑‍💻',power:'Starter persona. Build combos to evolve.',need:0,energy:3},
{name:'Spreadsheet Adept',icon:'📊',power:'Position cards give +1 Sanity.',need:2,energy:3},
{name:'Meeting Mage',icon:'🧙‍♂️',power:'Memo burnout reduced by 1.',need:4,energy:4},
{name:'Director of Chaos',icon:'🔥',power:'Combo attacks hit bosses harder.',need:7,energy:4},
{name:'Out Of Office Ascended',icon:'🌌',power:'Maximum energy and escape potential.',need:10,energy:5}
];
const cards=[
{name:'Reply All Disaster',type:'memo',cost:1,rarity:'Rare',icon:'📧💥',burnout:2,sanity:0,rank:0,damage:3,tags:['email','chaos'],flavor:'Your typo reached everyone.'},
{name:'Budget Cuts',type:'memo',cost:1,rarity:'Common',icon:'✂️📉',burnout:1,sanity:-1,rank:0,damage:2,tags:['budget','chaos'],flavor:'Do more with less, then less with nothing.'},
{name:'Mandatory Overtime',type:'memo',cost:2,rarity:'Uncommon',icon:'🌙🖨️',burnout:3,sanity:-1,rank:0,damage:4,tags:['overtime','chaos'],flavor:'Your weekend evaporates.'},
{name:'Mental Health Day',type:'pto',cost:1,rarity:'Rare',icon:'🧠🌤️',burnout:-3,sanity:3,rank:0,damage:0,tags:['pto','heal'],flavor:'You ignore Slack and remember birds exist.'},
{name:'Vacation Approved',type:'pto',cost:2,rarity:'Epic',icon:'🏖️✅',burnout:-4,sanity:4,rank:0,damage:0,tags:['pto','heal'],flavor:'The approval email glows like treasure.'},
{name:'Work From Home',type:'pto',cost:1,rarity:'Uncommon',icon:'🏠🩳',burnout:-1,sanity:2,rank:0,damage:1,tags:['pto','remote'],flavor:'Camera off. Soul on.'},
{name:'Promotion Opportunity',type:'position',cost:2,rarity:'Uncommon',icon:'🪜💼',burnout:1,sanity:0,rank:1,damage:2,tags:['career'],flavor:'More title. More meetings.'},
{name:'Executive Visibility',type:'position',cost:3,rarity:'Rare',icon:'👁️🏢',burnout:2,sanity:0,rank:2,damage:4,tags:['career'],flavor:'Leadership saw your name.'},
{name:'LinkedIn Thought Leader',type:'position',cost:2,rarity:'Epic',icon:'📣🦚',burnout:1,sanity:2,rank:1,damage:3,tags:['career','social'],flavor:'You post humbled and gain power.'},
{name:'Quiet Quit Ritual',type:'pto',cost:2,rarity:'Epic',icon:'🕯️🚪',burnout:-2,sanity:5,rank:0,damage:1,tags:['pto','remote'],flavor:'You become impossible to emotionally invoice.'}
];
let game;
function el(id){return document.getElementById(id)}
function draw(){return {...cards[Math.floor(Math.random()*cards.length)]};}
function safeText(id,value){const node=el(id);if(node)node.textContent=value;}
function safeHtml(id,value){const node=el(id);if(node)node.innerHTML=value;}
function pulse(id,cls){const node=el(id);if(!node)return;node.classList.remove(cls);void node.offsetWidth;node.classList.add(cls);}
function currentBoss(){return bosses[Math.min(game.bossIndex,bosses.length-1)];}
function start(){game={rank:0,burnout:0,sanity:5,xp:0,persona:0,energy:3,bossIndex:0,bossHp:bosses[0].hp,rival:{rank:1,burnout:0,sanity:6},hand:[draw(),draw(),draw(),draw(),draw()],played:[],lastCombo:'None',log:['Defeat corporate bosses, evolve your Persona, and escape.'],over:false};safeHtml('result','');safeHtml('pack','<div class="confidentialArt">CONFIDENTIAL<br><span>DO NOT OPEN</span></div>');safeText('combo','None');render();}
function combo(){const names=game.played.slice(-2).map(c=>c.name);const tags=game.played.flatMap(c=>c.tags||[]);let bonus='None';if(names.includes('Work From Home')&&names.includes('Quiet Quit Ritual')){game.sanity+=4;game.burnout=Math.max(0,game.burnout-2);game.bossHp-=game.persona>=3?4:2;bonus='Ghost Employee';}else if(tags.filter(t=>t==='career').length>=2){game.rank=Math.min(positions.length-1,game.rank+1);game.xp+=2;game.bossHp-=3;bonus='Career Ascension';}else if(tags.filter(t=>t==='pto').length>=2){game.sanity+=2;game.xp+=1;bonus='PTO Chain';}else if(tags.filter(t=>t==='chaos').length>=2){game.rival.burnout+=3;game.bossHp-=5;bonus='Corporate Death Spiral';}game.lastCombo=bonus;safeText('combo',bonus);if(bonus!=='None'){game.log.unshift('COMBO: '+bonus+' triggered.');pulse('comboViz','flash');}}
function evolve(){while(game.persona<personas.length-1&&game.xp>=personas[game.persona+1].need){game.persona++;game.log.unshift('PERSONA EVOLVED: '+personas[game.persona].name);pulse('persona','evolveFlash');}}
function bossCheck(){if(game.bossHp<=0){game.log.unshift('BOSS DEFEATED: '+currentBoss().name);game.bossIndex++;if(game.bossIndex>=bosses.length){game.over=true;safeHtml('result','<div class="win">You defeated the Corporate Machine and escaped.</div>');return;}game.bossHp=currentBoss().hp;game.xp+=2;game.hand.push(draw(),draw());pulse('rivalPosition','flash');}}
function check(){bossCheck();if(game.over)return;if(game.rank>=positions.length-1){game.over=true;safeHtml('result','<div class="win">You reached CEO final form.</div>');}else if(game.sanity>=28){game.over=true;safeHtml('result','<div class="win">You escaped the rat race.</div>');}else if(game.burnout>=12){game.over=true;safeHtml('result','<div class="lose">Burnout consumed you.</div>');}else if(game.rival.rank>=positions.length-1){game.over=true;safeHtml('result','<div class="lose">The Corporate Machine reached CEO before you.</div>');}}
function playCard(i){if(game.over)return;const c=game.hand[i];if(!c)return;if(game.energy<c.cost){game.log.unshift('Not enough energy for '+c.name+'.');pulse('energy','flashBad');render();return;}game.energy-=c.cost;let burn=c.burnout;if(c.type==='memo'&&game.persona>=2)burn=Math.max(0,burn-1);game.rank=Math.min(positions.length-1,game.rank+c.rank);game.burnout=Math.max(0,game.burnout+burn);game.sanity=Math.max(0,game.sanity+c.sanity+(c.type==='position'&&game.persona>=1?1:0));game.bossHp-=c.damage||0;game.xp+=c.rarity==='Epic'?2:c.rarity==='Rare'?1:0;game.played.push(c);game.log.unshift(c.name+': '+c.flavor);game.hand.splice(i,1);pulse('rivalStats','hitFlash');combo();evolve();check();render();}
function endTurn(){if(game.over)return;game.hand.push(draw());const boss=currentBoss();game.burnout+=boss.attack;game.log.unshift(boss.name+' attacks for '+boss.attack+' burnout.');const move=Math.random();if(move>.7){game.rival.rank=Math.min(positions.length-1,game.rival.rank+1);game.log.unshift('Rival played Promotion Ladder Scam.');}else if(move>.38){game.burnout+=1;game.log.unshift('Rival played Emergency Alignment Meeting.');}else{game.rival.sanity+=2;game.log.unshift('Rival played Delegation Shield.');}game.played=[];game.lastCombo='None';game.energy=personas[game.persona].energy;safeText('combo','None');check();render();}
function openPack(){const pulls=[draw(),draw(),draw()];game.hand.push(...pulls);safeHtml('pack',pulls.map(c=>cardHtml(c,-1)).join(''));game.log.unshift('Opened a booster pack: '+pulls.map(c=>c.name).join(', '));pulse('pack','packBurst');render();}
function cardHtml(c,i){return '<article class="card '+c.type+' '+c.rarity.toLowerCase()+'" '+(i>=0?'onclick="playCard('+i+')"':'')+'><div class="cardTop"><span>'+c.type.toUpperCase()+' • ⚡'+c.cost+'</span><b>'+c.rarity+'</b></div><div class="art '+c.type+'Art"><div class="comicFace">'+c.icon+'</div><div class="burst"></div></div><h2>'+c.name+'</h2><p>'+c.flavor+'</p><div class="stats"><span>🔥 '+(c.burnout>0?'+':'')+c.burnout+'</span><span>🧠 '+(c.sanity>0?'+':'')+c.sanity+'</span><span>⚔️ '+(c.damage||0)+'</span></div></article>';}
function render(){const p=personas[game.persona];const b=currentBoss();safeText('burnout',game.burnout);safeText('sanity',game.sanity);safeText('sanityTop',Math.max(0,game.sanity*6));safeText('coffee',7+game.persona);safeText('energy',game.energy+'/'+p.energy);safeText('rivalPosition',b.name);safeText('rivalStats','Boss HP '+game.bossHp+'/'+b.hp+' • Energy '+game.energy+'/'+p.energy);const bar=el('bossBar');if(bar)bar.style.width=Math.max(0,(game.bossHp/b.hp)*100)+'%';safeHtml('persona','<div class="personaCard level'+(game.persona+1)+'"><div class="personaIcon">'+p.icon+'</div><div><h2>'+p.name+' Lv.'+(game.persona+1)+'</h2><p>'+p.power+'</p><b>XP '+game.xp+' • Energy '+game.energy+'</b></div><button>VIEW EVOLUTION ↑</button></div>');safeHtml('comboViz',comboMarkup());safeHtml('hand',game.hand.map((c,i)=>cardHtml(c,i)).join(''));safeHtml('log',game.log.slice(0,10).map(x=>'<p>'+x+'</p>').join(''));const bm=el('burnoutMeter');if(bm)bm.value=game.burnout;const sm=el('sanityMeter');if(sm)sm.value=game.sanity;}
function comboMarkup(){if(game.lastCombo==='Ghost Employee')return '<div class="comboCards"><div>🏠<br>WORK FROM HOME</div><b>+</b><div>🕯️<br>QUIET QUIT</div><b>=</b><div class="comboResult">👻<br>GHOST EMPLOYEE<br>x4</div></div>';if(game.lastCombo==='None')return '<div class="comboEmpty">Play matching tags to unleash combos.</div>';return '<div class="comboResult big">'+game.lastCombo+'!</div>';}
document.addEventListener('DOMContentLoaded',function(){if(el('newGame'))el('newGame').onclick=start;if(el('endTurn'))el('endTurn').onclick=endTurn;if(el('openPack'))el('openPack').onclick=openPack;start();});